logging:
    level:
        web: DEBUG
spring:
    application:
        name: ${APP_NAME:Interview Demo Sample}
    devtools:    
        restart:      
            enabled: 'true'      
            poll-interval: '2s'      
            quiet-period: '1s'      
            additional-paths:      
                - src/main/java/
server:
    port: ${APP_PORT:8080}
springdoc:
    swagger-ui:
        path: ${SWAGGER_PATH:/swagger-ui.html}

